name: Pipeline CICD projet Master

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: master_node_app

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: lancer les tests
        run: ls -lah
